services:
  s3d:
    image: ghcr.io/siafoundation/s3d:latest
    volumes:
      - s3d-data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build: .
    ports:
      - "8001:8000"
    environment:
      BOT_TOKEN: "8469946262:AAH1-Uksp-IywacGuJFzHjY9dRCxEdZCR6w"
      S3_ENDPOINT: "http://s3d:8000"
      S3_ACCESS_KEY: "JI55REOJFJPNKT3YP7BA"
      S3_SECRET_KEY: "Ctj6dXADHDmY50f1PwjZg7fT+2r06DuoNwjKEYab"
      BUCKET_NAME: "cgu-logs"
      MAX_RESULTS: "50"
      QUERY_TIMEOUT_SEC: "30"
      KEEP_ALIVE_INTERVAL: "5"
    depends_on:
      - s3d
    restart: unless-stopped

volumes:
  s3d-data: